name: Init admin user

on:
  workflow_dispatch:

jobs:
  create-admin-user:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Update VPS Configuration via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs: POSTGRES_USER, POSTGRES_PASS, POSTGRES_SCHEMA, POSTGRES_URL
          script: |
            docker run --rm \
              --network nr31_nr31-network \
              -e POSTGRES_USER=$POSTGRES_USER \
              -e POSTGRES_PASS=$POSTGRES_PASS \
              -e POSTGRES_SCHEMA=$POSTGRES_SCHEMA \
              -e POSTGRES_URL=$POSTGRES_URL \
              -v $(pwd):/opt/output \
              postgres:15-alpine \
              /bin/sh -c "
                echo 'Starting Admin Setup...'

                if [ -f /opt/output/admin_credentials.txt ]; then
                  echo 'Credentials file already exists. Skipping setup.'
                  exit 0
                fi

                ADMIN_PASS=\$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)
                
                export PGPASSWORD=\$POSTGRES_PASS

                psql \"\${POSTGRES_URL#jdbc:}\" -U \$POSTGRES_USER -d \$POSTGRES_SCHEMA -c \"
                  CREATE EXTENSION IF NOT EXISTS pgcrypto;
                  WITH new_user AS (
                      INSERT INTO users (username, password_hash, email, email_verified)
                      SELECT 'superadmin', crypt('\$ADMIN_PASS', gen_salt('bf')), 'superadmin@nr31.org', true
                      WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'superadmin')
                      RETURNING id
                  ),
                  target_role AS (
                      SELECT id FROM roles WHERE name = 'SUPER_ADMIN' LIMIT 1
                  )
                  INSERT INTO user_roles (user_id, role_id)
                  SELECT new_user.id, target_role.id
                  FROM new_user, target_role;
                \"

                # Output to the mounted VPS directory
                echo 'Username: superadmin' > /opt/output/admin_credentials.txt
                echo \"Password: \$ADMIN_PASS\" >> /opt/output/admin_credentials.txt
                chmod 600 /opt/output/admin_credentials.txt
                
                echo 'Admin generated successfully.'
              "
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER || vars.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS || vars.POSTGRES_PASS }}
          POSTGRES_SCHEMA: ${{ secrets.POSTGRES_SCHEMA || vars.POSTGRES_SCHEMA }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL || vars.POSTGRES_URL }}
