name: Update config

on:
  workflow_dispatch:

jobs:
  update-server-configs:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Update VPS Configuration via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            set -e
            
            echo "Current user: $(whoami)"
            
            export PATH=$PATH:/usr/bin:/usr/local/bin:/snap/bin
            
            which docker
            docker compose version
            
            echo "Navigating to /opt/nr31..."
            cd /opt/nr31
            
            git fetch origin
            git reset --hard origin/main
            
            docker compose up -d --remove-orphans --force-recreate
            
            docker image prune -f
