name: Update config

on:
  workflow_dispatch:

jobs:
  update-server-configs:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Update VPS Configuration via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs: GHCR_PAT, GHCR_USER
          script: |
            echo $GHCR_PAT | docker login ghcr.io -u $GHCR_USER --password-stdin

            cd /opt/nr31

            git fetch origin
            git reset --hard origin/main

            docker compose pull
            
            docker compose up -d --remove-orphans --force-recreate
            
            docker image prune -f

            docker logout ghcr.io
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GHCR_USER: ${{ secrets.GHCR_USER }}
